name: Release Package

on:
  workflow_dispatch:  # 添加手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y tar gzip

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Run package script
        run: |
          # 添加执行权限
          chmod +x package-tar.sh
          # 以root权限运行打包脚本
          sudo ./package-tar.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: safe-rm.tar.gz
          name: Release ${{ env.DATE }}
          tag_name: release-${{ env.DATE }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}